window.designResources = [
  ["gallery","60fps","Recordings of interfaces that move well.","https://60fps.design/"],
  ["gallery","Awwwards","Awards celebrating exceptional digital web craft.","https://www.awwwards.com/"],
  ["gallery","Cosmos","Visual moodboarding and creative inspiration engine.","https://www.cosmos.so/"],
  ["gallery","Curated Design","Web design sorted by aesthetic style.","https://www.curated.design/"],
  ["gallery","Layers","Platform for sharing design work publicly.","https://layers.to/"],
  ["gallery","Minimal Gallery","Showcase of minimal and restrained websites.","https://minimal.gallery/"],
  ["gallery","Mobbin","Real mobile and web product flows.","https://mobbin.com/"],
  ["gallery","Saaspo","Curated SaaS landing page designs.","https://www.saaspo.com/"],
  ["gallery","SEESAW","Design inspiration organized by page section.","https://www.seesaw.website/"],
  ["gallery","Supahero","Curated collection of website hero sections.","https://supahero.io/"],
  ["gallery","Imageory","Visual gallery pairing images with prompts.","https://www.imageory.in/"],
  ["gallery","Backgrounds Supply","Handcrafted website backgrounds ready to use.","https://backgrounds.supply/"],
  ["gallery","Venust Backgrounds","Free AI-generated backgrounds with original prompts.","https://backgrounds.venust.ai/"],
  ["gallery","Details","Micro-interaction analysis of top digital products.","https://www.details.so/"],
  ["gallery","Sombra","Showcase of dark-mode website interfaces.","https://sombra.design/"],
  ["gallery","Dribbble","Global community sharing design concepts.","https://dribbble.com/"],
  ["gallery","Behance","Adobe showcase for creative portfolios.","https://www.behance.net/"],
  ["gallery","Recent Design","Weekly selection of award-worthy websites.","https://recent.design/"],
  ["gallery","navbar.design","Curated gallery of navigation bar patterns.","https://navbar.design/"],
  ["gallery","footer.design","Curated gallery of creative website footers.","https://footer.design/"],
  ["gallery","Land-book","Landing pages organized by industry.","https://land-book.com/"],
  ["gallery","Collect UI","Daily UI inspiration tagged by component.","https://collectui.com/"],
  ["gallery","SiteInspire","Showcase of fine web design craft.","https://www.siteinspire.com/"],
  ["gallery","Lapa Ninja","Curated gallery of responsive landing pages.","https://www.lapa.ninja/"],
  ["gallery","UX Archive","Historical archive of mobile onboarding flows.","https://uxarchive.com/"],
  ["gallery","Screenlane","Searchable gallery of interface screens.","https://screenlane.com/"],
  ["gallery","Flowbase","Premium UI components and interaction patterns.","https://www.flowbase.co/"],
  ["gallery","Hover States","Showcase of innovative interactive web design.","https://hoverstat.es/"],
  ["gallery","SaaSFrame","Hundreds of SaaS marketing page screenshots.","https://www.saasframe.io/"],
  ["gallery","Landingfolio","Extensive library of landing page designs.","https://www.landingfolio.com/"],
  ["gallery","Pttrns","Directory of mobile user interface patterns.","https://pttrns.com/"],
  ["gallery","One Page Love","Showcase of single-page website designs.","https://onepagelove.com/"],
  ["gallery","Designspiration","Creative search platform for visual art.","https://www.designspiration.com/"],
  ["gallery","Best Website Gallery","Curated archive of exceptional websites.","https://bestwebsite.gallery/"],
  ["gallery","Inspiration Grid","Online magazine celebrating creative visual design.","https://theinspirationgrid.com/"],
  ["gallery","Scrnshts","Curated App Store screenshot designs.","https://scrnshts.club/"],
  ["gallery","Are.na","Collaborative research and visual bookmarking platform.","https://www.are.na/"],
  ["gallery","Appinspo","Curated mobile application design gallery.","https://www.appinspo.com/"],
  ["gallery","Dark Mode Design","Showcase celebrating dark-mode websites.","https://www.darkmodedesign.com/"],
  ["gallery","Pinterest","Visual discovery engine for creative ideas.","https://www.pinterest.com/"],
  ["gallery","navbar.gallery","Focused collection of modern navigation bars.","https://navbar.gallery/"],
  ["gallery","posts.design","Curated social media graphic design archive.","https://posts.design/"],
  ["gallery","loadmo.re","Gallery of experimental mobile website designs.","https://loadmo.re/"],
  ["gallery","inspora.design","Archive of contemporary visual web design.","https://www.inspora.design/"],
  ["gallery","cta.gallery","Curated call-to-action button and banner designs.","https://cta.gallery/"],
  ["gallery","desengs.com","Directory of design engineering portfolios and lore.","https://desengs.com/"],
  ["gallery","isthereanytool","Directory of lesser-known design, craft, and AI tools.","https://isthereanytool.app/"],
  ["gallery","designeng.tools","Curated design engineering tools, resources, and inspiration.","https://designeng.tools/"],
  ["gallery","bestdesignsonx.com","Curated design-forward creators and posts on X.","https://bestdesignsonx.com/"],
  ["gallery","Design Bookmark","Directory of design resources and links.","https://designbookmark.com/"],
  ["gallery","Rebrand Gallery","Brand redesigns compared before and after.","https://rebrand.gallery/"],
  ["gallery","Curations","Library of curated digital design assets.","https://curations.supply/"],
  ["gallery","Landing Love","Delightful landing pages organized by animation.","https://landing.love/"],
  ["gallery","Motionimo","Extensive library of motion design clips.","https://motionimo.xyz/"],
  ["gallery","before.click","Showcase of high-converting app screenshot concepts.","https://before.click/"],
  ["gallery","Swiped","Standout design posts from social platforms.","https://swiped.design/"],
  ["gallery","Landdding","Daily catalogue of creative landing pages.","https://landdding.com/"],
  ["gallery","designengineer.tools","Essential tools tailored for design engineers.","https://designengineer.tools/"],
  ["gallery","Insposite","Directory of design references and tools.","https://www.insposite.com/"],
  ["gallery","Loader Buttons","Gallery of 25 loading button animations.","https://loader-buttons.appllama.io/"],
  ["gallery","What Ships","Standout product launch demo videos on X.","https://whatships.com/"],
  ["gallery","GreatStuff","Carefully vetted archive of creative tools.","https://greatstuff.fyi/"],
  ["gallery","Great Apps","Weekly gallery highlighting exceptional iOS apps.","https://greatapps.fyi/"],
  ["gallery","Curated Domains","Brands using creative top-level domain names.","https://curated.domains/"],
  ["gallery","Sections.wtf","Real-world website section and hero gallery.","https://sections.wtf/"],
  ["gallery","Browse.cool","Websites chosen for exceptional tactile feel.","https://browse.cool/"],
  ["gallery","Folios Gallery","Selective directory of outstanding designer portfolios.","https://folios.gallery/"],
  ["gallery","wwwtf.site","Quirky and experimental interactive web corners.","https://wwwtf.site/"],
  ["gallery","Early","Discovery platform for early-stage software products.","https://www.early.tools/"],
  ["gallery","OpenAlternative","Open-source alternatives to popular SaaS tools.","https://openalternative.co/"],
  ["gallery","Everywhere Tools","Open-source creative tools for design craft.","https://everywhere.tools/"],
  ["gallery","Jessy In's Gallery","Collaborative moodboard of unique visual finds.","https://gallery.jessyin.world/"],
  ["gallery","Wall of Portfolios","Design engineering and product portfolio showcases.","https://www.wallofportfolios.in/"],
  ["gallery","Detail Design","Archive of thoughtful software micro-interactions.","https://detail.design/"],
  ["gallery","Betwn Studios","Studio crafting modern SaaS web experiences.","https://betwnstudios.com/"],
  ["gallery","SaaS Landing Page","Showcase of top SaaS landing pages.","https://saaslandingpage.com/"],
  ["gallery","Best SaaS Web Designs","Curated inspiration gallery of SaaS website design.","https://bestsaaswebdesigns.com/"],
  ["gallery","A1","Website design inspiration gallery.","https://www.a1.gallery/"],
  ["gallery","UIBook","Real web pages and sections, curated with taste.","https://uibook.art/"],
  ["gallery","Dev Chauhan","Frontend developer portfolio from India.","https://devchauhan.in/"],
  ["gallery","Godly","Curated gallery of outstanding website design.","https://godly.design/"],
  ["gallery","Herogrids","Curated collection of hero section designs.","https://herogrids.com/"],

  ["interface","Figma","Collaborative interface design and prototyping platform.","https://figma.com/"],
  ["interface","Framer","Visual canvas for designing and publishing websites.","https://framer.com/"],
  ["interface","make.design","AI generator turning prompts into polished designs.","https://make.design/"],
  ["interface","Penpot","Open-source web design platform supporting SVG.","https://penpot.app/"],
  ["interface","Spline","Browser-based 3D design software with physics.","https://spline.design/"],
  ["interface","Interface Craft","Articles exploring modern digital interface craftsmanship.","https://www.interfacecraft.dev/"],
  ["interface","UI Labs","Laboratory deconstructing animated UI components.","https://www.uilabs.dev/"],
  ["interface","UIWTF","Showcase of experimental web interface patterns.","https://uiw.tf/"],
  ["interface","Lab01","Refined UI experiments from a studio.","https://lab01.dev/"],
  ["interface","design.dev","AI-assisted design token and system editor.","https://design.dev/"],
  ["interface","UI Playbook","Guide to common UI component states.","https://uiplaybook.dev/"],

  ["reading","Refactoring UI","Practical design guide for building interfaces.","https://refactoringui.com/"],
  ["reading","Practical Typography","Essential book covering typographic rules and layout.","https://practicaltypography.com/"],
  ["reading","web.dev","Guidance on web performance and modern standards.","https://web.dev/"],
  ["reading","Inclusive Components","Pattern library teaching accessible component design.","https://inclusive-components.design/"],
  ["reading","Josh Comeau","Interactive tutorials breaking down CSS mechanics.","https://joshwcomeau.com/"],
  ["reading","Design Books","Directory of essential design literature by discipline.","https://design-books.com/"],
  ["reading","Design System Checklist","Comprehensive checklist for production design systems.","https://designsystemchecklist.com/"],
  ["reading","Learn UI","Video course teaching practical user interface design.","https://learn-ui.com/"],
  ["reading","Design Spells","Dissecting subtle design details in software.","https://designspells.com/"],
  ["reading","Good UI","Evidence-based UI design patterns and data.","https://goodui.org/"],
  ["reading","Abduzeedo","Daily design blog sharing visual inspiration.","https://abduzeedo.com/"],
  ["reading","UX Collective","Curated publication sharing critical UX essays.","https://uxdesign.cc/"],
  ["reading","Smashing Magazine","Reliable resource for web designers and developers.","https://www.smashingmagazine.com/"],
  ["reading","Codrops","Blog publishing creative frontend experiments and tutorials.","https://tympanus.net/codrops/"],
  ["reading","Muzli","Daily digest curating latest design trends.","https://muz.li/"],
  ["reading","Boxes and Arrows","Journal dedicated to information architecture craft.","https://boxesandarrows.com/"],
  ["reading","Designer News","Community-driven news feed highlighting design stories.","https://www.designernews.co/"],
  ["reading","Web Designer Depot","Design publication covering web standards and tools.","https://www.webdesignerdepot.com/"],
  ["reading","Designmodo","Articles and tools covering web design.","https://designmodo.com/"],
  ["reading","99designs Discover","Design blog exploring creative branding insights.","https://99designs.com/discover"],
  ["reading","Interfaces","Monthly digital publication exploring digital interfaces.","https://interfaces.dev/"],
  ["reading","Making Software","Essays examining how tools shape design.","https://www.makingsoftware.com/"],
  ["reading","Visual Rambling","Personal visual essays exploring interface design.","https://visualrambling.space/"],
  ["reading","Degreeless Design","Curated roadmap for mastering product design.","https://www.degreeless.design/"],
  ["reading","SVG Guide","Guide to mastering SVG markup and animations.","https://www.svg.guide/"],
  ["reading","Animations.dev","Course on creating web animations that feel right.","https://www.animations.dev/"],
  ["reading","UI Skills","Course teaching techniques for designing with AI.","https://ui-skills.com/"],
  ["reading","AI for UI","Course teaching AI workflows for interfaces.","https://aiforui.dev/"],
  ["reading","UI Land","Interviews with leading design engineers on craft.","https://ui.land/"],
  ["reading","Laws of UX","Psychological principles that influence interface usability.","https://lawsofux.com/"],
  ["reading","User Interface Wiki","Knowledge base documenting interface guidelines and rules.","https://userinterface.wiki/"],
  ["reading","The Shape of AI","Pattern library highlighting AI interface design.","https://www.shapeof.ai/"]
];
